
CREATE TABLE SCHOOL
(
SCHOOLNAME varchar(100),
ADDRESS1 VARCHAR(100),
ADDRESS2 VARCHAR(100),
WEB VARCHAR(20),
STARTDATE DATETIME,
STARTTIME VARCHAR(20),
ENDTIME VARCHAR(20),
INTERVAL VARCHAR(20),
PERIODHOUR FLOAT,
NUMPERIOD INTEGER,
STARTGRADE INTEGER,
ENDGRADE INTEGER,
NOCLASSROOM INTEGER,
MONDAY BIT,
TUESDAY BIT,
WEDNESSDAY BIT,
THURSDAY BIT,
FRIDAY BIT,
SATURDAY BIT,
SUNDAY BIT,
TYPE VARCHAR(30),
DESCRIPTIONS VARCHAR(100),
CONSTRAINT SchNa PRIMARY KEY(SCHOOLNAME)
)


CREATE TABLE IDS
(
IDS varchar(10) ,
TEMIDS	varchar(10),
STUIDS varchar(10),
STAFFIDS varchar(10),
SubjectID varchar(10),
MEMBERIDS varchar(10),
RECEPID varchar(10),
BOOKIDS varchar(10),
ReserveNo varchar(10),
LibTransNo varchar(10),
)


CREATE TABLE BOOK
(
BookID INTEGER,
ISBN VARCHAR(20),
Title VARCHAR(50),
AuthorName VARCHAR(50),
Publisher VARCHAR(50),
Y_OF_P INTEGER,
Edition INTEGER,
Language VARCHAR(50),
Overnight VARCHAR(5),
Catagory VARCHAR(50),
N_OF_Co INTEGER,
Donation VARCHAR(50),
Price FLOAT,
CONSTRAINT Book_id PRIMARY KEY(BookID)
)

CREATE TABLE COPY_OF_BOOK
(
BookID INTEGER,
AccessNo VARCHAR(15),
BookStatus VARCHAR(5) DEFAULT 'YES',
CONSTRAINT Access_id PRIMARY KEY(AccessNo),
CONSTRAINT bid FOREIGN KEY(BookID) REFERENCES BOOK ON DELETE CASCADE
)

CREATE TABLE STAFF
(
StaffID VARCHAR(10),
FullName VARCHAR(50),
RegNo VARCHAR(20),
PostHeld VARCHAR(30),
Grade VARCHAR(20),
Nationality VARCHAR(20),
D_Of_B DATETIME,
NIC VARCHAR(15),
Sex VARCHAR(10),
Religion VARCHAR(10),
CivilStatus VARCHAR(15),
Street VARCHAR(50),
City VARCHAR(50),
Pri_Tp VARCHAR(15),
Per_Tp VARCHAR(15),
WOP VARCHAR(20),
FileNo VARCHAR(15),
Qualification VARCHAR(50),
D_Of_Appionment DATETIME,
Salary FLOAT,
Service VARCHAR(50),
Category VARCHAR(30),
Work_Hours FLOAT,
CONSTRAINT StID PRIMARY KEY(StaffID)
)


CREATE TABLE LEAVINGSTAFF
(
LeStID VARCHAR(10),
FullName VARCHAR(50),
RegNo VARCHAR(20),
PostHeld VARCHAR(30),
Grade VARCHAR(20),
Nationality VARCHAR(20),
D_Of_B DATETIME,
NIC VARCHAR(15),
Sex VARCHAR(10),
Religion VARCHAR(10),
CivilStatus VARCHAR(15),
Street VARCHAR(50),
City VARCHAR(50),
Pri_Tp VARCHAR(15),
Per_Tp VARCHAR(15),
WOP VARCHAR(20),
FileNo VARCHAR(15),
Qualification VARCHAR(50),
Service VARCHAR(50),
Category VARCHAR(30),
D_Of_Appionment DATETIME,
Lea_Date DATETIME DEFAULT GETDATE(),
CONSTRAINT Restid PRIMARY KEY(LeStID)
)


CREATE TABLE STAFFATTENDANCE
(
StaffID VARCHAR(10),
AttDate DATETIME,
ComingTime DATETIME,
GoingTime DATETIME,
CONSTRAINT AtdPri PRIMARY KEY(StaffID,AttDate),
CONSTRAINT AtdStf FOREIGN KEY(StaffID) REFERENCES STAFF ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE TABLE SHORTLEAVES
(
StaffID VARCHAR(10),
Dates DATETIME,
GoingTime DATETIME,
ComingTime DATETIME,
LeaveType VARCHAR(20) DEFAULT 'Short',
CONSTRAINT Shopri PRIMARY KEY(StaffID,Dates),
CONSTRAINT ShoStf FOREIGN KEY(StaffID) REFERENCES STAFF ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE TABLE TEMPSTUDENTS
(
TemID INTEGER,
StudentName VARCHAR(50),
FatherName VARCHAR(50),
D_Of_Birth DATETIME,
Religion VARCHAR(20),
Street VARCHAR(50),
City VARCHAR(30),
FatherJob VARCHAR(50),
Telephone VARCHAR(15),
LastGrade VARCHAR(10),
Pri_School_Add VARCHAR(100),
Class VARCHAR(10),
CONSTRAINT Tid PRIMARY KEY(TemID)
)



CREATE TABLE MAINSTUDENTS
(
StuID VARCHAR(10),
StudentName VARCHAR(50),
FatherName VARCHAR(50),
D_Of_Admin DATETIME,
D_Of_Birth DATETIME,
Religion VARCHAR(20),
Street VARCHAR(50),
City VARCHAR(30),
FatherJob VARCHAR(50),
Telephone VARCHAR(15),
LastGrade VARCHAR(10),
Pri_School_Add VARCHAR(100),
AdminGrade VARCHAR(10),
CONSTRAINT Sid PRIMARY KEY(StuID)
)

CREATE TABLE CLASS
(
ClassName VARCHAR(10),
No_Of_Students INTEGER, 
Medium VARCHAR(20),
CONSTRAINT Cl1 PRIMARY KEY(ClassName)
)


CREATE TABLE ACTIVESTUDENT
(
StuID VARCHAR(10),
Curr_Class VARCHAR(10),
CONSTRAINT ActStd PRIMARY KEY(StuID),
CONSTRAINT ActStd1 FOREIGN KEY(StuID) REFERENCES MAINSTUDENTS ON DELETE CASCADE ON UPDATE CASCADE,
)


CREATE TABLE OLDBOYS
(
StuID VARCHAR(10),
D_Of_Leave DATETIME,
LastGrade VARCHAR(10),
Purpose_Of_Leave VARCHAR(500),
Descriptions VARCHAR(500),
CONSTRAINT OldSID PRIMARY KEY(StuID),
CONSTRAINT OldTid1 FOREIGN KEY(StuID) REFERENCES MAINSTUDENTS ON DELETE CASCADE ON UPDATE CASCADE,
)



CREATE TABLE LIBRARYMEMBER
(
MemID VARCHAR(10),
SCID VARCHAR(10),
MemName VARCHAR(50),
Status VARCHAR(10),
Membership VARCHAR(5),
LendStatus VARCHAR(10) DEFAULT 'YES',
StartClass VARCHAR(10) DEFAULT 20,
CONSTRAINT MID PRIMARY KEY(MemID),
)


CREATE TABLE LENDING
(
TransNo INTEGER,
MemID VARCHAR(10),
AccessNo VARCHAR(15),
BorrowDate DATETIME,
DueDate DATETIME,
ReturnDate DATETIME,
Fine FLOAT,
FinePaid VARCHAR(5),
Transact VARCHAR(10) DEFAULT 'LEND'
CONSTRAINT BD PRIMARY KEY(MemID,AccessNo,BorrowDate),
)


CREATE TABLE RESERVE
(
MemID VARCHAR(10),
AccessNo VARCHAR(15),
ReserveDate DATETIME,
ResStatus VARCHAR(5) DEFAULT 'RES',
CONSTRAINT RNo PRIMARY KEY(MemID,AccessNo,ReserveDate),
)


CREATE TABLE PAYMENTS
(
RecNo integer,
MemID VARCHAR(10),
Payment FLOAT,
Pay_Date DATETIME DEFAULT GETDATE(),
Pay_Status VARCHAR(20),
CONSTRAINT ReNo PRIMARY KEY(RecNo)
)


CREATE TABLE TERMAVG
(
StuID VARCHAR(10),
StudentName VARCHAR(50),
Grade VARCHAR(10),
Term1 FLOAT DEFAULT 0,
Term2 FLOAT DEFAULT 0,
Term3 FLOAT DEFAULT 0,
CONSTRAINT YE PRIMARY KEY(StuID),
CONSTRAINT SID3 FOREIGN KEY(StuID) REFERENCES ACTIVESTUDENT ON DELETE CASCADE ON UPDATE CASCADE,
)

CREATE TABLE YEARAVERAGE
(
StuID VARCHAR(10),
Year6 FLOAT DEFAULT 0,
Year7 FLOAT DEFAULT 0,
Year8 FLOAT DEFAULT 0,
Year9 FLOAT DEFAULT 0,
Year10 FLOAT DEFAULT 0,
Year11 FLOAT DEFAULT 0,
Year12 FLOAT DEFAULT 0,
Year13 FLOAT DEFAULT 0,
CONSTRAINT YEAVG PRIMARY KEY(StuID),
)


CREATE TABLE CLUB
(
CName VARCHAR(30),
StartYear DATETIME,
Descriptions VARCHAR(100),
CONSTRAINT CID PRIMARY KEY(CName)
)


CREATE TABLE CLUBMEMBER
(
CName VARCHAR(30),
StuID VARCHAR(10),
JoinDate DATETIME,
Descriptions VARCHAR(500)
CONSTRAINT CM PRIMARY KEY(CName,StuID)
)

CREATE TABLE STREAM
(
StrID VARCHAR(10),
StrName VARCHAR(10)UNIQUE,
CONSTRAINT Str1 PRIMARY KEY(StrID),
)

CREATE TABLE FOLLOWSTREAM
(
StuID VARCHAR(10),
StrName VARCHAR(10),
Subject1 VARCHAR(15),
Subject2 VARCHAR(15),
Subject3 VARCHAR(15),
Subject4 VARCHAR(15),
CONSTRAINT FStr PRIMARY KEY(StuID,StrName),
CONSTRAINT fsid FOREIGN KEY(StuID) REFERENCES MAINSTUDENTS ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE TABLE ALRESULT
(
StuID VARCHAR(10),
StrName VARCHAR(10),
IndexNo VARCHAR(10),
AlYear integer,
Times integer,
Subject1 VARCHAR(5),
Subject2 VARCHAR(5),
Subject3 VARCHAR(5),
Subject4 VARCHAR(5),
English VARCHAR(5),
General VARCHAR(5),
DistrictRank VARCHAR(5),
IslandRank VARCHAR(5),
ZScore FLOAT,
CONSTRAINT AlStr PRIMARY KEY(StuID,AlYear),
CONSTRAINT Alsid FOREIGN KEY(StuID) REFERENCES MAINSTUDENTS ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE TABLE OLRESULT
(
StuID VARCHAR(10),
IndexNo VARCHAR(10),
OlYear integer,
Maths VARCHAR(5),
Science VARCHAR(5),
Social VARCHAR(5),
English VARCHAR(5),
Language VARCHAR(50),
Religion VARCHAR(50),
Aesthetic VARCHAR(50),
Technical VARCHAR(50),
Additional1 VARCHAR(50),
Additional2 VARCHAR(50),
CONSTRAINT OlStr PRIMARY KEY(StuID,OlYear),
CONSTRAINT Olsid FOREIGN KEY(StuID) REFERENCES MAINSTUDENTS ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE OLSUBJECT
(
SubjectNames VARCHAR(50),
Category VARCHAR(50),
Status VARCHAR(10) DEFAULT 'YES'
)

CREATE TABLE SUBJECT
(
SubjectID VARCHAR(10),
SubjectNames VARCHAR(50),
Category VARCHAR(50),
CONSTRAINT SubID1 PRIMARY KEY(SubjectID)
)

CREATE TABLE ALSUBJECT
(
SubjectNames VARCHAR(50),
Stream VARCHAR(20),
CONSTRAINT ALSUB PRIMARY KEY(SubjectNames,Stream)
)

CREATE TABLE TEACHSUBJECT
(
StaffID VARCHAR(10),
SubjectID VARCHAR(10),
Category VARCHAR(50),
Descriptions VARCHAR(100),
CONSTRAINT TeaSub PRIMARY KEY(StaffID,SubjectID),
CONSTRAINT StId10 FOREIGN KEY(StaffID) REFERENCES STAFF ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT SubNu FOREIGN KEY(SubjectID) REFERENCES SUBJECT ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE CLUBMAINTAINCE
(
CName VARCHAR(30),
Years DATETIME, 
Super_StaffID VARCHAR(10),
Super_StafName VARCHAR(50),
Pres_StuID VARCHAR(10),
Pres_StuName VARCHAR(100),
Sec_StuID VARCHAR(10),
Sec_StuName VARCHAR(100),
Descriptions VARCHAR(500),
CONSTRAINT ClubMain PRIMARY KEY(CName,Years),
)


CREATE TABLE TEACHERSCHEDULE
(
Curr_Year integer,
ClassName VARCHAR(10),
StaffID VARCHAR(10),
SubjectNames VARCHAR(50),
Period integer,
ClassTeacher VARCHAR(5)
CONSTRAINT teashe PRIMARY KEY(Curr_Year,ClassName,StaffID,SubjectNames)
)


CREATE TABLE MEDICALLEAVES
(
StaffID VARCHAR(10),
CurrentYear INTEGER,
OneYearBefore INTEGER DEFAULT 0,
TwoYearsBefore INTEGER DEFAULT 0,
Nopay INTEGER DEFAULT 0
CONSTRAINT StfID PRIMARY KEY(StaffID)
CONSTRAINT MediStf FOREIGN KEY(StaffID) REFERENCES STAFF ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE CASUALLEAVES
(
StaffID VARCHAR(10),
TotalDays INTEGER,
UseDays INTEGER DEFAULT 0
CONSTRAINT CasStfID PRIMARY KEY(StaffID)
CONSTRAINT CasStf FOREIGN KEY(StaffID) REFERENCES STAFF ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE STAFFLEAVES
(
StaffID VARCHAR(10),
DateTo DATETIME,
DateFrom DATETIME,
LeaveType VARCHAR(20),
LeaveDetails VARCHAR(21),
CONSTRAINT LeaStfID PRIMARY KEY(StaffID,DateTo),
CONSTRAINT LeaStf FOREIGN KEY(StaffID) REFERENCES STAFF ON DELETE CASCADE ON UPDATE CASCADE
)



CREATE TABLE TIMETABLE
(
StaffID VARCHAR(10),
Days VARCHAR(10),
ClassName VARCHAR(10),
SubjectNames VARCHAR(50),
Period VARCHAR(5),
CONSTRAINT Tim PRIMARY KEY(StaffID,Days,ClassName,SubjectNames,Period),
CONSTRAINT TimeStf FOREIGN KEY(StaffID) REFERENCES STAFF ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT TimeClass FOREIGN KEY(ClassName) REFERENCES CLASS ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE USERGROUP
(
GroupName VARCHAR(20),
Administrator BIT,
MasterSetup BIT,
Staff BIT,
ClubMaintain BIT,
Students BIT,
NewStudent BIT,
StudentLea BIT,
Result BIT,
TermAve BIT,
OldStudnt BIT,
Library BIT,
Report BIT,
CONSTRAINT GrNa PRIMARY KEY(GroupName)
)


CREATE TABLE LOGIN
(
StaffID VARCHAR(10) UNIQUE,
Passwords VARCHAR(10),
LastModiDate DATETIME DEFAULT GETDATE(),
GroupName VARCHAR(20) DEFAULT 'Staff',
CONSTRAINT LNo PRIMARY KEY(StaffID),
)


CREATE TABLE ADMINISTRATOR
(
login	varchar(10) DEFAULT 'Administrator',
Passwords VARCHAR(10),
LastModiDate DATETIME DEFAULT GETDATE(),
GroupName VARCHAR(20) DEFAULT 'Admin',
CONSTRAINT lno1 PRIMARY KEY(login)
)


CREATE TABLE GRADEANDSUBJECTS
(
Grade Varchar(10),
TotalSubjects Varchar(5),
Subject1 Varchar(50),
No_of_Per_Sub1 Varchar(5),
Subject2 Varchar(50),
No_of_Per_Sub2 Varchar(5),
Subject3 Varchar(50),
No_of_Per_Sub3 Varchar(5),
Subject4 Varchar(50),
No_of_Per_Sub4 Varchar(5),
Subject5 Varchar(50),
No_of_Per_Sub5 Varchar(5),
Subject6 Varchar(50),
No_of_Per_Sub6 Varchar(5),
Subject7 Varchar(50),
No_of_Per_Sub7 Varchar(5),
Subject8 Varchar(50),
No_of_Per_Sub8 Varchar(5),
Subject9 Varchar(50),
No_of_Per_Sub9 Varchar(5),
Subject10 Varchar(50),
No_of_Per_Sub10 Varchar(5),
Subject11 Varchar(50),
No_of_Per_Sub11 Varchar(5),
Subject12 Varchar(50),
No_of_Per_Sub12 Varchar(5),
CONSTRAINT Gr PRIMARY KEY(Grade)
)






select * from GRADEANDSUBJECTS where Grade=6
select 	Subject1,Subject2,Subject3,Subject4 As rer ff,
	Subject5,Subject6,Subject7,Subject8,
	Subject9,Subject10,Subject11,Subject12
 from GRADEANDSUBJECTS where Grade=6






select * from ACTIVESTUDENT
select A.StuID,M.StudentName,M.FatherName,A.Curr_Class from ACTIVESTUDENT A,MAINSTUDENTS M where A.StuID=M.StuID
select A.StuID,M.StudentName,M.FatherName,A.Curr_Class from ACTIVESTUDENT A,MAINSTUDENTS M where A.StuID=M.StuID and A.Curr_Class='8 A'






SELECT * FROM IDS
select * from BOOK
select * from COPY_OF_BOOK
select * from LEAVINGSTAFF
select * from STAFF
select * from STAFFATTENDANCE
select * from SHORTLEAVES
select * from MEDICALLEAVES
select * from CASUALLEAVES
select * from STAFFLEAVES
select * from CLASS
select * from TEMPSTUDENTS
select * from MAINSTUDENTS
select * from ACTIVESTUDENT
select * from OLDBOYS
select * from LIBRARYMEMBER
select * from LENDING
select * from RESERVE
select * from TERMAVG
select * from YEARAVERAGE
select * from CLUB
select * from CLUBMEMBER
select * from OLRESULT
select * from ALRESULT
select * from FOLLOWSTREAM
select * from STREAM
select * from ALSUBJECT
select * from SUBJECT
select * from OLSUBJECT
select * from TEACHSUBJECT
select * from CLUBMAINTAINCE
select * from TEACHERSCHEDULE
select * from TIMETABLE
select * from USERGROUP
select * from LOGIN
select * from GRADEANDSUBJECTS


drop table GRADEANDSUBJECTS
drop table TIMETABLE
drop table ADMINISTRATOR
drop table LOGIN
drop table USERGROUP
drop table MNUPERMISSION
drop table MEDICALLEAVES
drop table CASUALLEAVES
drop table STAFFLEAVES
drop table TEACHERSCHEDULE
drop table STAFFLEAVES
drop table CLUBMAINTAINCE
drop table TEACHSUBJECT
drop table SUBJECT
drop table OLSUBJECT
drop table ALRESULT
drop table OLRESULT
drop table ALSUBJECT
drop table FOLLOWSTREAM
drop table STREAM
drop table CLUBMEMBER
drop table CLUB
drop table TERMAVG
drop table YEARAVERAGE
drop table RESERVE
drop table LENDING
drop table LIBRARYMEMBER
drop table OLDBOYS
drop table ACTIVESTUDENT
drop table MAINSTUDENTS
drop table TEMPSTUDENTS
drop table CLASS
drop table SHORTLEAVES
drop table STAFFATTENDANCE
drop table LEAVINGSTAFF
drop table MEDICALLEAVES
drop table STAFF
drop table COPY_OF_BOOK
drop table BOOK
drop table IDS
drop table PAYMENTS
drop table SCHOOL
